name: CI
on: [push]
jobs:
  build:
    name: Lint and build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: latest

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
